// Generated by tools/make_fonts.py. Do not edit; rerun the script.
#pragma once

#include "font.h"

extern const Font sora_title;  // Sora-SemiBold.ttf, 14 px
extern const Font sora_title_regular;  // Sora-Regular.ttf, 14 px
extern const Font sora_artist;  // Sora-Medium.ttf, 11 px
extern const Font sora_clock;  // Sora-Light.ttf, 58 px
extern const Font sora_micro;  // Sora-Regular.ttf, 9 px
