#!/usr/bin/env python3
"""Turn the root certificates in tools/certs/ into BearSSL trust anchors.

Writes src/trust_anchors.c (constant data in flash, no RAM).

    .venv/bin/pip install cryptography
    .venv/bin/python tools/make_trust_anchors.py

To add a root: put its PEM in tools/certs/ and rerun. On macOS you can export
one from the system store, e.g.
    security find-certificate -p -c "ISRG Root X1" \\
        /System/Library/Keychains/SystemRootCertificates.keychain > tools/certs/ISRG_Root_X1.pem
"""
import glob
import os

from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CURVES = {"secp256r1": "BR_EC_secp256r1", "secp384r1": "BR_EC_secp384r1",
          "secp521r1": "BR_EC_secp521r1"}


def c_bytes(name, data):
    rows = [", ".join(f"0x{b:02X}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    return f"static const unsigned char {name}[] = {{\n    " + ",\n    ".join(rows) + "\n};\n"


def main():
    out = ["// Generated by tools/make_trust_anchors.py from tools/certs/*.pem.",
           "// Do not edit; rerun the script.", "",
           '#include "trust_anchors.h"', ""]
    entries = []
    for i, path in enumerate(sorted(glob.glob(os.path.join(ROOT, "tools", "certs", "*.pem")))):
        cert = x509.load_pem_x509_certificate(open(path, "rb").read())
        name = cert.subject.rfc4514_string()
        out.append(f"// {name}, expires {cert.not_valid_after_utc:%Y-%m-%d}")
        out.append(c_bytes(f"TA{i}_DN", cert.subject.public_bytes()))
        key = cert.public_key()
        if isinstance(key, rsa.RSAPublicKey):
            n = key.public_numbers()
            out.append(c_bytes(f"TA{i}_N", n.n.to_bytes((n.n.bit_length() + 7) // 8, "big")))
            out.append(c_bytes(f"TA{i}_E", n.e.to_bytes((n.e.bit_length() + 7) // 8, "big")))
            pkey = (f"{{BR_KEYTYPE_RSA, {{.rsa = {{(unsigned char *)TA{i}_N, sizeof TA{i}_N, "
                    f"(unsigned char *)TA{i}_E, sizeof TA{i}_E}}}}}}")
        elif isinstance(key, ec.EllipticCurvePublicKey):
            q = key.public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)
            out.append(c_bytes(f"TA{i}_Q", q))
            pkey = (f"{{BR_KEYTYPE_EC, {{.ec = {{{CURVES[key.curve.name]}, "
                    f"(unsigned char *)TA{i}_Q, sizeof TA{i}_Q}}}}}}")
        else:
            raise SystemExit(f"{path}: unsupported key type")
        entries.append(f"    {{{{(unsigned char *)TA{i}_DN, sizeof TA{i}_DN}}, BR_X509_TA_CA, {pkey}}},")
        print(f"{os.path.basename(path)}: {name}")

    out.append("const br_x509_trust_anchor TRUST_ANCHORS[] = {")
    out += entries
    out.append("};")
    out.append("const size_t TRUST_ANCHORS_NUM = sizeof TRUST_ANCHORS / sizeof TRUST_ANCHORS[0];")
    with open(os.path.join(ROOT, "src", "trust_anchors.c"), "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
